-- ElectroIsla 360 v9.8.2
-- Categorías iniciales
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.categories enable row level security;

insert into public.categories (name, sort_order)
values ('Alimentos', 1), ('Electrodomésticos', 2), ('COMBOS', 3)
on conflict (name) do nothing;
