-- ElectroIsla 360 v9.8.2 — categorías
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.categories enable row level security;

drop policy if exists "Categorias visibles públicamente" on public.categories;
create policy "Categorias visibles públicamente" on public.categories for select to anon using (available = true);
drop policy if exists "Categorias autenticadas pueden consultar" on public.categories;
create policy "Categorias autenticadas pueden consultar" on public.categories for select to authenticated using (true);
drop policy if exists "Administradores pueden agregar categorias" on public.categories;
create policy "Administradores pueden agregar categorias" on public.categories for insert to authenticated with check (true);
drop policy if exists "Administradores pueden modificar categorias" on public.categories;
create policy "Administradores pueden modificar categorias" on public.categories for update to authenticated using (true) with check (true);
drop policy if exists "Administradores pueden eliminar categorias" on public.categories;
create policy "Administradores pueden eliminar categorias" on public.categories for delete to authenticated using (true);

insert into public.categories (name,sort_order,available) values
  ('Alimentos',1,true),('Electrodomésticos',2,true),('COMBOS',3,true)
on conflict (name) do nothing;
